"""Regenerate the development-screen tables (markdown) from the committed result JSONs: results/DEV_SCREENS.md.  Nothing is copied by hand."""
import json
from pathlib import Path
import pandas as pd
import nd_core as core
import nd_analyze_select as sel

HERE = Path(__file__).resolve().parent; R = HERE / "results"
LEARNER_SCREENS = [("screen1", "Learner variants with random labels: decisive-only, no-tie, no-not_apply, mirror-symmetric head, filename metadata, pseudo-labelling (20 dev seeds)"),
                   ("screen2a", "Time-contrastive adapter on the SimCLR features (20 dev seeds)"),
                   ("screen2b", "GP preference learner, prior-centred Bayes head (independent / type-coupled), CV-chosen schedule (10 dev seeds; cv_schedule only 4)"),
                   ("screen3_cal", "Calibration check for non-decisive judgments (split A, temperature fitted on validation groups)"),
                   ("screen5", "Reference-anchor weight 0 / 1 / 4 and Rao-Kupper tie likelihood (11 dev seeds, stopped)"),
                   ("screen6", "Ensembles of 5 / 10 heads"),
                   ("screen7_anchor", "Reference-anchor weight and bad-image weight grid (20 dev seeds)"),
                   ("screen8_all", "Anchor weight with all ideal images as anchors (20 dev seeds)"),
                   ("screen9", "Anchor weight 8 with all ideal anchors: schedule and 1/N variants (dev)"),
                   ("screen10", "Anchor weight 8 with all ideal anchors combined with symmetric head, ensemble, metadata, GP (dev)")]
SELECTION_SCREENS = [("sel1", "Selectors: vopt_u, goal-oriented vopt_amb, mirror consistency, vopt_cons, GP variance (20 dev seeds, baseline head)"),
                     ("sel2", "Selectors: raw-space design and power-sampled batches (20 dev seeds)"), ("sel3", "Selection with the GP learner in the loop"), ("sel4", "Committee of MLP head and GP as acquisition"),
                     ("sel5_cold", "Cold start (10 random initial judgments)"), ("sel6", "Selection with the anchor-weighted model")]


def frame_of(name):
    rows = [r for f in sorted((R / name).glob("seed*_*.json")) for r in json.loads(f.read_text())] if (R / name).exists() else []
    return pd.DataFrame(rows)


def md(df, floatfmt="{:.4f}"):
    cols = list(df.columns); out = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in df.iterrows(): out.append("| " + " | ".join(floatfmt.format(v) if isinstance(v, float) else str(v) for v in r) + " |")
    return "\n".join(out)


def main():
    lines = ["# Development screens (generated by nd_make_report_tables.py; development seeds only, not confirmatory evidence)", "",
             "Gains are paired over the same label sets; log-loss gain = reference - cell (positive is better); intervals are paired bootstrap over seeds.", ""]
    for name, title in LEARNER_SCREENS:
        f = frame_of(name)
        if f.empty or "selector" in f: continue
        t = core.paired_table(f, "baseline"); keep = ["split", "learner", "n_seeds"] + [c for m in ("auc", "acc", "ll", "cal_ll") for c in (f"{m}_gain", f"{m}_lo", f"{m}_hi") if f"{m}_gain" in t]
        lines += [f"## {name}: {title}", "", md(t[keep]), ""]
    for name, title in SELECTION_SCREENS:
        f = frame_of(name)
        if f.empty: continue
        t = sel.table(f, metrics=("auc", "acc", "ll")); keep = ["split", "selector", "learner", "n_seeds"] + [c for m in ("auc", "acc", "ll") for c in (m, f"{m}_lo", f"{m}_hi", f"{m}_p")]
        lines += [f"## {name}: {title}", "", "Gain over random selection with the baseline head.", "", md(t[keep]), ""]
    (R / "DEV_SCREENS.md").write_text("\n".join(lines)); print("wrote", R / "DEV_SCREENS.md")


if __name__ == "__main__":
    main()
