#!/usr/bin/env python3
"""Regenerates every confirmatory table of the new-methods study (pre-registrations 1-5) into results/new_methods/CONFIRMATORY_TABLES.md.
Per-seed gain over a baseline averaged over budgets 10/20/40/60 and over the four split x condition cells; one-sided Wilcoxon signed-rank; Holm over the pre-registered family."""
import numpy as np, pandas as pd
from scipy.stats import wilcoxon
import new_methods_analyze as an

COL = {name: (m, sign) for m, sign, name in an.METRICS}
_cache = {}
def per(run):
    if run not in _cache: f = an.load(run); _cache[run] = f.groupby(["split", "cond", "seed", "family", "budget"])[[m for m, _, _ in an.METRICS]].mean().reset_index()
    return _cache[run]
def seeds_gain(run, method, base, name):
    m, sign = COL[name]; t = per(run).pivot_table(index=["split", "cond", "seed", "budget"], columns="family", values=m); d = (t[method] - t[base]) * (1 if sign > 0 else -1)
    cells = d.groupby(["split", "cond", "seed"]).mean().unstack(["split", "cond"]).dropna()   # complete seeds only
    return cells.mean(axis=1), cells
def holm(p):
    p = np.asarray(p, float); order = np.argsort(p); out = np.empty(len(p)); run = 0
    for rank, i in enumerate(order): run = max(run, min(1.0, (len(p) - rank) * p[i])); out[i] = run
    return out
def table(run, tests, title, note=""):
    rows = []
    for method, base, name in tests:
        s, cells = seeds_gain(run, method, base, name); rows.append({"method": method, "vs": base, "metric": name, "n_seeds": len(s), "mean_gain": s.mean(), "sd": s.std(), "seeds_better": (s > 0).mean(), "p": wilcoxon(s, alternative="greater").pvalue,
                                                                  **{f"{a}_{b[:3]}": cells[(a, b)].mean() for a, b in cells.columns}})
    t = pd.DataFrame(rows); t["holm_p"] = holm(t.p.values)
    out = [f"### {title}", note, "", "| method | vs | metric | seeds | mean gain | sd | seeds better | one-sided p | Holm p | A single | A seq | B single | B seq |", "|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    fmt = lambda x: "<0.0001" if x < 1e-4 else f"{x:.4f}"
    for r in t.itertuples(): out.append(f"| {r.method} | {r.vs} | {r.metric} | {r.n_seeds} | {r.mean_gain:+.4f} | {r.sd:.4f} | {r.seeds_better:.0%} | {fmt(r.p)} | {fmt(r.holm_p)} | {r.A_sin:+.4f} | {r.A_seq:+.4f} | {r.B_sin:+.4f} | {r.B_seq:+.4f} |")
    return "\n".join(out) + "\n"
doc = ["# Confirmatory tables of the new-methods study (generated by `new_methods_final_tables.py`)\n"]
doc.append(table("confirm", [(m, "random", n) for m in ("vopt_u", "vopt_u_inf1") for n in ("logloss", "AUC", "acc")], "Pre-registration 1: seeds 700-734 (Holm over these 6 tests)"))
doc.append(table("confirm2", [(m, "random", n) for m in ("vopt_u", "vopt_u_inf1", "fisher_dopt", "bald_decisive") for n in ("AUC", "acc")], "Pre-registration 2: seeds 800-834, replication (Holm over these 8 tests; log-loss secondary below)"))
doc.append(table("confirm2", [(m, "random", "logloss") for m in ("vopt_u", "vopt_u_inf1", "fisher_dopt", "bald_decisive")], "Pre-registration 2, secondary: log-loss (uncorrected within these 4)"))
doc.append(table("confirm3_coldstart", [(m, "random", n) for m in ("vopt_u", "vopt_u_inf1", "fisher_dopt", "bald_decisive") for n in ("logloss", "AUC", "acc")], "Pre-registration 3: cold start (10 random initial judgments), seeds 900-934 (Holm over 12 tests)"))
doc.append(table("confirm4_htr", [(m, b, n) for m in ("vopt_htr", "fisher_htr") for b in ("random", "random_htr") for n in ("htr_acc", "htr_auc", "htr_ll")], "Pre-registration 4: HTR-targeted design, seeds 1000-1034 (Holm over 12 tests)"))
doc.append(table("confirm5_priority", [("vopt_hw4", "random", n) for n in ("htr_acc", "htr_auc", "htr_ll", "acc", "AUC")], "Pre-registration 5: priority-weighted design (HTR weight 4), seeds 1100-1134 (Holm over these 5 tests)"))
doc.append(table("confirm5_priority", [("vopt_hw4", "random", n) for n in ("logloss", "t13_acc", "tc6x2_acc", "t1x1_acc")] + [("vopt_hw4", "random_htr", n) for n in ("htr_acc", "htr_auc", "htr_ll", "acc", "AUC")] + [("vopt_hw4", "vopt_u", n) for n in ("htr_acc", "htr_auc", "htr_ll", "acc", "AUC")],
                 "Pre-registration 5, secondary comparisons (uncorrected)"))
from pathlib import Path
(an.ROOT / "CONFIRMATORY_TABLES.md").write_text("\n".join(doc)); print("written", len(doc))
